# Generated by Django 4.2.7 on 2024-10-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_taskmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='manual_item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID прибора'),
        ),
    ]
